CREATE TABLE "LINK_CLIENT_ROLE" (
  "ID" BIGSERIAL NOT NULL,
  "CLIENT_ID" VARCHAR(256) NOT NULL,
  "ROLE_ID" BIGINT NOT NULL,
  CONSTRAINT client_fk FOREIGN KEY("CLIENT_ID") REFERENCES "oauth_client_details"("client_id"),
  CONSTRAINT role_fk FOREIGN KEY("ROLE_ID") REFERENCES "ROLE"("ID"),
  PRIMARY KEY ("ID")
);
